name: misc-utils-py

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --flake8 --black --pydocstyle --mypy --cov=src --cov-fail-under=90 --cov-branch --cov-report=term-missing
